server:
    port: 8181
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1/user_dummy?useSSL=false&serverTimezone=Asia/Jakarta&verifyServerCertificate=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Demoneyesky0
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
